// AUTO-GENERATED by build_next.py — do not edit by hand
export const catalogStyle = `
  :root {
    --bg: #f5eee1;
    --surface: #ffffff;
    --surface-2: #ece2d0;
    --ink: #241b14;
    --ink-muted: #6b5d4d;
    --gold: #a67c33;
    --rust: #9c4419;
    --line: #ddd0ba;
  }
  @media (prefers-color-scheme: dark) {
    :root:not([data-theme="light"]) {
      --bg: #17110c;
      --surface: #221a13;
      --surface-2: #2a2018;
      --ink: #f3ead9;
      --ink-muted: #c2b19a;
      --gold: #d4ad68;
      --rust: #cc6a35;
      --line: #3a2d21;
    }
  }
  :root[data-theme="dark"] {
    --bg: #17110c;
    --surface: #221a13;
    --surface-2: #2a2018;
    --ink: #f3ead9;
    --ink-muted: #c2b19a;
    --gold: #d4ad68;
    --rust: #cc6a35;
    --line: #3a2d21;
  }

  * { box-sizing: border-box; }
  html { -webkit-text-size-adjust: 100%; }
  body {
    margin: 0;
    background: var(--bg);
    color: var(--ink);
    font-family: 'Manrope', system-ui, -apple-system, sans-serif;
    line-height: 1.5;
    overflow-x: hidden;
  }
  a { color: inherit; }

  .wrap { max-width: 1180px; margin: 0 auto; padding: 0 24px; }

  /* ---------- ANNOUNCEMENT BAR ---------- */
  .announce-bar {
    background: var(--gold);
    color: #17110c;
    text-align: center;
    padding: 9px 24px;
    font-size: 13px;
    font-weight: 700;
    letter-spacing: 0.03em;
  }
  .announce-bar strong { font-weight: 900; }

  /* ---------- HEADER ---------- */
  .site-header {
    background: var(--ink);
    border-bottom: 1px solid rgba(255,255,255,0.08);
    position: sticky;
    top: 0;
    z-index: 50;
  }
  .site-header-inner {
    max-width: 1180px;
    margin: 0 auto;
    padding: 0 24px;
    display: flex;
    align-items: center;
    gap: 40px;
    height: 58px;
  }
  .site-logo {
    text-decoration: none;
    flex-shrink: 0;
    display: flex;
    align-items: center;
  }
  .site-logo-img {
    height: 36px;
    width: auto;
    display: block;
    filter: invert(1);
    mix-blend-mode: screen;
  }
  .header-nav {
    display: flex;
    align-items: center;
    gap: 6px;
    overflow-x: auto;
    scrollbar-width: none;
    flex: 1;
  }
  .header-nav::-webkit-scrollbar { display: none; }
  .header-nav a {
    font-size: 12.5px;
    font-weight: 700;
    letter-spacing: 0.06em;
    text-transform: uppercase;
    color: rgba(243,234,217,0.7);
    text-decoration: none;
    padding: 6px 12px;
    border-radius: 4px;
    white-space: nowrap;
    transition: color 0.15s, background 0.15s;
  }
  .header-nav a:hover {
    color: #f3ead9;
    background: rgba(255,255,255,0.08);
  }
  .header-nav a.highlight {
    color: var(--gold);
    border: 1px solid rgba(166,124,51,0.5);
  }
  .header-nav a.highlight:hover {
    background: rgba(166,124,51,0.15);
  }
  .header-wa {
    flex-shrink: 0;
    display: inline-flex;
    align-items: center;
    gap: 6px;
    font-size: 12px;
    font-weight: 700;
    color: #f3ead9;
    background: #25963f;
    padding: 7px 14px;
    border-radius: 999px;
    text-decoration: none;
    transition: filter 0.15s;
  }
  .header-wa:hover { filter: brightness(1.1); }
  @media (max-width: 700px) {
    .site-header-inner { gap: 16px; }
    .header-wa { display: none; }
  }

  /* ---------- HERO ---------- */
  .hero {
    border-bottom: 1px solid var(--line);
  }
  .brandmark {
    font-family: 'Manrope', sans-serif;
    font-weight: 800;
    letter-spacing: 0.32em;
    font-size: 13px;
    color: var(--gold);
    margin: 0 0 18px;
    text-shadow: 0 1px 4px rgba(0,0,0,0.5);
  }
  .hero h1 {
    font-family: 'Fraunces', serif;
    font-weight: 600;
    font-size: clamp(36px, 6vw, 80px);
    line-height: 0.95;
    letter-spacing: -0.01em;
    margin: 0 0 20px;
    text-wrap: balance;
    color: #f3ead9;
    text-shadow: 0 2px 12px rgba(0,0,0,0.6);
  }
  .hero h1 em {
    font-style: italic;
    font-weight: 500;
    color: var(--gold);
  }
  .hero p.lede {
    font-size: 16px;
    color: rgba(243,234,217,0.85);
    max-width: 40ch;
    margin: 0 0 22px;
    text-shadow: 0 1px 6px rgba(0,0,0,0.5);
  }
  .hero-promo {
    display: inline-block;
    font-family: 'Manrope', sans-serif;
    font-weight: 800;
    font-size: 13px;
    letter-spacing: 0.06em;
    text-transform: uppercase;
    color: #17110c;
    background: var(--gold);
    padding: 8px 16px;
    border-radius: 999px;
    box-shadow: 0 4px 16px rgba(0,0,0,0.35);
  }
  /* ---------- HERO BANNER full-width ---------- */
  .hero-banner {
    position: relative;
    width: 100%;
    height: 72vh;
    min-height: 420px;
    max-height: 700px;
    overflow: hidden;
  }
  .hero-banner-slide {
    position: absolute;
    inset: 0;
    opacity: 0;
    transition: opacity 0.8s ease;
    pointer-events: none;
  }
  .hero-banner-slide.is-active {
    opacity: 1;
    pointer-events: auto;
  }
  .hero-banner-slide img {
    width: 100%;
    height: 100%;
    object-fit: cover;
    object-position: center top;
    display: block;
  }
  /* dark gradient overlay so text is legible */
  .hero-banner::after {
    content: '';
    position: absolute;
    inset: 0;
    background: linear-gradient(
      90deg,
      rgba(15,10,6,0.72) 0%,
      rgba(15,10,6,0.40) 55%,
      rgba(15,10,6,0.05) 100%
    );
    pointer-events: none;
    z-index: 1;
  }
  /* text overlay on top of gradient */
  .hero-banner-overlay {
    transition: opacity 0.6s ease;
    position: absolute;
    inset: 0;
    z-index: 2;
    display: flex;
    flex-direction: column;
    justify-content: center;
    padding: 0 clamp(24px, 6vw, 100px);
    max-width: 640px;
  }
  .hero-banner-dots {
    position: absolute;
    bottom: 20px;
    right: 20px;
    display: flex;
    gap: 8px;
    align-items: center;
    z-index: 3;
  }
  .hero-banner-dot {
    width: 8px;
    height: 8px;
    border-radius: 50%;
    background: rgba(243,234,217,0.4);
    border: none;
    padding: 0;
    cursor: pointer;
    transition: background 0.3s, transform 0.3s;
  }
  .hero-banner-dot.is-active {
    background: #f3ead9;
    transform: scale(1.35);
  }
  .hero-banner-prev,
  .hero-banner-next {
    position: absolute;
    top: 50%;
    transform: translateY(-50%);
    background: rgba(23,17,12,0.45);
    border: none;
    color: #f3ead9;
    width: 40px;
    height: 40px;
    border-radius: 50%;
    cursor: pointer;
    font-size: 20px;
    line-height: 1;
    display: flex;
    align-items: center;
    justify-content: center;
    transition: background 0.2s;
    z-index: 3;
  }
  .hero-banner-prev { left: 14px; }
  .hero-banner-next { right: 14px; }
  .hero-banner-prev:hover,
  .hero-banner-next:hover { background: rgba(23,17,12,0.8); }
  .hero-below {
    border-top: 1px solid var(--line);
    padding: 18px 0 0;
  }
  .collections-nav {
    display: flex;
    flex-wrap: wrap;
    gap: 10px 22px;
    padding: 22px 0 24px;
    margin-top: 36px;
    border-top: 1px solid var(--line);
    font-size: 13px;
    font-weight: 600;
    letter-spacing: 0.04em;
    text-transform: uppercase;
    color: var(--ink-muted);
  }
  .collections-nav a { text-decoration: none; }
  .collections-nav a:hover { color: var(--gold); }
  .collections-nav span.count {
    font-weight: 500;
    color: var(--ink-muted);
    text-transform: none;
    letter-spacing: 0;
  }

  .features {
    display: flex;
    flex-wrap: wrap;
    gap: 10px 30px;
    padding: 18px 0 40px;
    font-size: 13.5px;
    color: var(--ink-muted);
  }
  .features li { list-style: none; display: flex; gap: 8px; align-items: baseline; }
  .features li b { color: var(--ink); font-weight: 700; }

  /* ---------- PROMO PAGUE 2 LEVE 3 ---------- */
  .promo-section {
    padding: 60px 0 20px;
    scroll-margin-top: 20px;
  }
  .promo-head {
    border-top: 3px solid var(--gold);
    padding-top: 28px;
    margin-bottom: 32px;
    display: flex;
    align-items: baseline;
    gap: 20px;
    flex-wrap: wrap;
  }
  .promo-badge-big {
    display: inline-flex;
    align-items: center;
    gap: 10px;
    background: var(--gold);
    color: #17110c;
    font-family: 'Manrope', sans-serif;
    font-weight: 900;
    font-size: 14px;
    letter-spacing: 0.06em;
    text-transform: uppercase;
    padding: 8px 18px;
    border-radius: 999px;
  }
  .promo-head h2 {
    font-family: 'Fraunces', serif;
    font-weight: 600;
    font-size: 38px;
    margin: 0;
  }
  .promo-head h2 em { font-style: italic; color: var(--gold); }
  .promo-head p {
    margin: 0;
    color: var(--ink-muted);
    font-size: 15px;
    flex-basis: 100%;
    max-width: 60ch;
  }
  .promo-grid {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 26px;
  }
  /* promo card — mesmo estilo mas com ribbon dourado */
  .promo-card {
    background: var(--surface);
    border: 1px solid var(--gold);
    border-radius: 6px;
    overflow: hidden;
    display: flex;
    flex-direction: column;
    position: relative;
  }
  .promo-ribbon {
    position: absolute;
    top: 12px;
    left: -2px;
    background: var(--gold);
    color: #17110c;
    font-size: 10.5px;
    font-weight: 900;
    letter-spacing: 0.06em;
    text-transform: uppercase;
    padding: 4px 10px 4px 12px;
    border-radius: 0 3px 3px 0;
    z-index: 2;
    box-shadow: 2px 2px 6px rgba(0,0,0,0.2);
  }
  .promo-price-row {
    display: flex;
    flex-direction: column;
    gap: 2px;
  }
  .promo-price-tag {
    font-size: 11px;
    font-weight: 700;
    letter-spacing: 0.05em;
    text-transform: uppercase;
    color: var(--gold);
  }
  .promo-price-kit {
    font-family: 'Fraunces', serif;
    font-weight: 600;
    font-size: 22px;
    color: var(--ink);
    font-variant-numeric: tabular-nums;
  }
  .promo-price-kit small {
    font-size: 13px;
    color: var(--ink-muted);
    font-family: 'Manrope', sans-serif;
    font-weight: 500;
  }
  .promo-cta {
    align-self: flex-start;
    font-size: 12px;
    font-weight: 700;
    letter-spacing: 0.03em;
    color: #f3ead9;
    background: var(--gold);
    border: none;
    padding: 8px 14px;
    border-radius: 999px;
    text-decoration: none;
    transition: filter 0.15s;
    white-space: nowrap;
  }
  .promo-cta:hover { filter: brightness(0.9); }
  .promo-howto {
    background: var(--surface-2);
    border: 1px solid var(--line);
    border-radius: 8px;
    padding: 24px 28px;
    margin: 36px 0 8px;
    display: flex;
    gap: 32px;
    flex-wrap: wrap;
    align-items: center;
  }
  .promo-howto-steps {
    display: flex;
    gap: 24px;
    flex-wrap: wrap;
    flex: 1;
  }
  .promo-step {
    display: flex;
    align-items: flex-start;
    gap: 12px;
  }
  .promo-step-num {
    width: 32px;
    height: 32px;
    border-radius: 50%;
    background: var(--gold);
    color: #17110c;
    font-weight: 900;
    font-size: 14px;
    display: flex;
    align-items: center;
    justify-content: center;
    flex-shrink: 0;
  }
  .promo-step-text strong { display: block; font-size: 14px; font-weight: 700; }
  .promo-step-text span { font-size: 13px; color: var(--ink-muted); }
  @media (max-width: 900px) {
    .promo-grid { grid-template-columns: repeat(2, 1fr); }
  }
  @media (max-width: 560px) {
    .promo-grid { grid-template-columns: 1fr; }
  }

  /* ---------- COLLECTIONS ---------- */
  .collection { padding: 54px 0 10px; scroll-margin-top: 20px; }
  .collection-head {
    display: flex;
    align-items: baseline;
    gap: 18px;
    flex-wrap: wrap;
    border-top: 1px solid var(--line);
    padding-top: 22px;
    margin-bottom: 28px;
  }
  .collection-head h2 {
    font-family: 'Fraunces', serif;
    font-weight: 600;
    font-size: 34px;
    margin: 0;
  }
  .collection-head p {
    margin: 0;
    color: var(--ink-muted);
    font-size: 15px;
  }

  .grid {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 26px;
  }
  .card {
    background: var(--surface);
    border: 1px solid var(--line);
    border-radius: 6px;
    overflow: hidden;
    display: flex;
    flex-direction: column;
  }
  .card-img {
    aspect-ratio: 4 / 5;
    overflow: hidden;
    background: var(--surface-2);
  }
  .zoom-trigger {
    display: block;
    width: 100%;
    height: 100%;
    padding: 0;
    margin: 0;
    border: 0;
    background: none;
    cursor: zoom-in;
  }
  .zoom-trigger:focus-visible {
    outline: 2px solid var(--gold);
    outline-offset: -2px;
  }
  .card-img img {
    width: 100%;
    height: 100%;
    object-fit: cover;
    display: block;
    transition: transform 0.5s ease;
  }
  .card:hover .card-img img { transform: scale(1.045); }

  /* ---------- LIGHTBOX ---------- */
  .lightbox {
    position: fixed;
    inset: 0;
    background: rgba(15, 11, 7, 0.86);
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 32px;
    z-index: 100;
    opacity: 0;
    visibility: hidden;
    transition: opacity 0.2s ease;
  }
  .lightbox.is-open {
    opacity: 1;
    visibility: visible;
  }
  .lightbox-fig {
    max-width: min(92vw, 900px);
    max-height: 92vh;
    margin: 0;
    display: flex;
    flex-direction: column;
    gap: 12px;
    align-items: center;
  }
  .lightbox-fig img {
    max-width: 100%;
    max-height: 78vh;
    width: auto;
    height: auto;
    object-fit: contain;
    border-radius: 4px;
    background: var(--surface);
  }
  .lightbox-fig figcaption {
    font-family: 'Fraunces', serif;
    font-size: 17px;
    color: #f3ead9;
  }
  .lightbox-close {
    position: absolute;
    top: 18px;
    right: 18px;
    width: 40px;
    height: 40px;
    border-radius: 50%;
    border: 1px solid rgba(243, 234, 217, 0.4);
    background: rgba(23, 17, 12, 0.5);
    color: #f3ead9;
    font-size: 20px;
    line-height: 1;
    cursor: pointer;
  }
  .lightbox-close:hover { border-color: #f3ead9; }
  .card-body {
    padding: 18px 18px 20px;
    display: flex;
    flex-direction: column;
    gap: 8px;
    flex: 1;
  }
  .card-body h3 {
    font-family: 'Fraunces', serif;
    font-weight: 600;
    font-size: 21px;
    margin: 0;
  }
  .card-body .desc {
    margin: 0;
    font-size: 14.5px;
    color: var(--ink-muted);
    flex: 1;
  }
  .card-body .tag {
    margin: 0;
    font-size: 13px;
    font-style: italic;
    color: var(--gold);
  }
  .specs {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 8px 10px;
    padding: 10px 0 2px;
    border-top: 1px dashed var(--line);
    margin-top: 2px;
  }
  .spec {
    display: flex;
    flex-direction: column;
    font-family: 'Manrope', sans-serif;
  }
  .spec span {
    font-size: 10.5px;
    text-transform: uppercase;
    letter-spacing: 0.06em;
    color: var(--ink-muted);
  }
  .spec b {
    font-size: 13.5px;
    font-variant-numeric: tabular-nums;
    font-weight: 700;
  }
  .buy-row {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 10px;
    margin-top: 6px;
  }
  .price {
    font-family: 'Fraunces', serif;
    font-weight: 600;
    font-size: 19px;
    font-variant-numeric: tabular-nums;
    color: var(--ink);
    white-space: nowrap;
  }
  .pill {
    align-self: flex-start;
    margin-top: 0;
    font-size: 12px;
    font-weight: 700;
    letter-spacing: 0.03em;
    color: var(--rust);
    border: 1px solid var(--rust);
    padding: 6px 12px;
    border-radius: 999px;
    text-decoration: none;
    transition: background 0.15s ease, color 0.15s ease;
  }
  .pill:hover {
    background: var(--rust);
    color: var(--surface);
  }

  /* ---------- SOCIAL ---------- */
  .social {
    padding: 54px 0 10px;
  }
  .social-head {
    border-top: 1px solid var(--line);
    padding-top: 22px;
    margin-bottom: 28px;
  }
  .social-head h2 {
    font-family: 'Fraunces', serif;
    font-weight: 600;
    font-size: 34px;
    margin: 0 0 6px;
  }
  .social-head p {
    margin: 0;
    color: var(--ink-muted);
    font-size: 15px;
    max-width: 60ch;
  }
  .social-grid {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 18px;
  }
  .social-card {
    position: relative;
    border-radius: 6px;
    overflow: hidden;
    aspect-ratio: 4 / 5;
    background: var(--surface-2);
  }
  .social-card img {
    width: 100%;
    height: 100%;
    object-fit: cover;
    display: block;
  }
  .social-card figcaption {
    position: absolute;
    left: 0;
    right: 0;
    bottom: 0;
    padding: 10px 12px;
    font-size: 12.5px;
    font-weight: 700;
    letter-spacing: 0.02em;
    color: #f3ead9;
    background: linear-gradient(to top, rgba(17,12,8,0.75), rgba(17,12,8,0));
  }
  @media (max-width: 900px) {
    .social-grid { grid-template-columns: repeat(2, 1fr); }
  }
  @media (max-width: 560px) {
    .social-grid { grid-template-columns: 1fr 1fr; gap: 10px; }
  }

  /* ---------- FOOTER ---------- */
  footer {
    margin-top: 70px;
    border-top: 1px solid var(--line);
    padding: 34px 0 50px;
    display: flex;
    justify-content: space-between;
    align-items: center;
    flex-wrap: wrap;
    gap: 14px;
  }
  footer .fm {
    font-family: 'Fraunces', serif;
    font-weight: 600;
    font-size: 20px;
  }
  footer .fnote {
    font-size: 13px;
    color: var(--ink-muted);
    max-width: 46ch;
  }
  footer .contacts {
    display: flex;
    align-items: center;
    gap: 18px;
    flex-wrap: wrap;
  }
  footer .ig {
    font-weight: 700;
    color: var(--gold);
    text-decoration: none;
  }
  footer .ig:hover { text-decoration: underline; }
  footer .wa {
    display: inline-flex;
    align-items: center;
    gap: 8px;
    font-weight: 700;
    font-size: 14px;
    color: #f3ead9;
    background: #25963f;
    padding: 10px 18px;
    border-radius: 999px;
    text-decoration: none;
    transition: filter 0.15s ease;
  }
  footer .wa:hover { filter: brightness(1.08); }

  /* ---------- FLOATING WHATSAPP ---------- */
  .wa-float {
    position: fixed;
    right: 20px;
    bottom: 20px;
    width: 56px;
    height: 56px;
    border-radius: 50%;
    background: #25963f;
    display: flex;
    align-items: center;
    justify-content: center;
    box-shadow: 0 6px 20px rgba(0,0,0,0.28);
    z-index: 50;
    transition: transform 0.15s ease;
  }
  .wa-float:hover { transform: scale(1.06); }
  .wa-float svg { width: 28px; height: 28px; }

  @media (max-width: 900px) {
    .hero-banner { height: 56vh; min-height: 320px; }
    .hero-banner-overlay { max-width: 80%; }
    .grid { grid-template-columns: repeat(2, 1fr); }
  }
  @media (max-width: 560px) {
    .hero-banner { height: 70vw; min-height: 260px; }
    .hero-banner::after { background: linear-gradient(180deg, rgba(15,10,6,0.2) 0%, rgba(15,10,6,0.75) 100%); }
    .hero-banner-overlay { justify-content: flex-end; padding: 0 20px 28px; max-width: 100%; }
    .hero h1 { font-size: clamp(28px, 8vw, 44px); }
    .hero p.lede { display: none; }
    .grid { grid-template-columns: 1fr; }
    footer { flex-direction: column; align-items: flex-start; }
  }

  @media (prefers-reduced-motion: reduce) {
    .card-img img { transition: none; }
    .lightbox { transition: none; }
  }
`;

export const catalogHtml = `<div class="announce-bar">Aproveite: comprando a partir de <strong>R$ 99,90</strong>, você ganha <strong>FRETE GRÁTIS</strong> na sua compra! 🚚</div>
<header class="site-header">
  <div class="site-header-inner">
    <a href="#" class="site-logo">
      <img src="/images/logo_top_sunglass.png" alt="TOP Sunglass" class="site-logo-img" />
    </a>
    <nav class="header-nav">
      <a href="#classico">Clássico</a>
      <a href="#streetwear">Streetwear</a>
      <a href="#praia">Praia</a>
      <a href="#esportivo">Esportivo</a>
      <a href="#social">Lookbook</a>
      <a href="#promo" class="highlight">🔥 Pague 2, Leve 3</a>
    </nav>
    <a href="https://wa.me/5511999999999" class="header-wa" target="_blank" rel="noopener">
      <svg width="15" height="15" viewBox="0 0 24 24" fill="currentColor"><path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347z"/><path d="M12 0C5.373 0 0 5.373 0 12c0 2.124.558 4.121 1.531 5.856L.057 23.852a.5.5 0 0 0 .614.614l6.057-1.49A11.945 11.945 0 0 0 12 24c6.627 0 12-5.373 12-12S18.627 0 12 0zm0 22c-1.907 0-3.695-.498-5.248-1.37l-.373-.214-3.865.95.978-3.79-.234-.388A9.964 9.964 0 0 1 2 12C2 6.477 6.477 2 12 2s10 4.477 10 10-4.477 10-10 10z"/></svg>
      WhatsApp
    </a>
  </div>
</header>
<div class="hero">
  <div class="hero-banner" id="heroBanner">
    <div class="hero-banner-slide is-active" data-no-overlay>
      <img src="/images/banner_pague2leve3.png" alt="Pague 2 Leve 3 — Top Sunglass" loading="eager" />
    </div>
    <div class="hero-banner-slide" data-no-overlay>
      <img src="/images/banner_estilo_que_marca.png" alt="Estilo Que Marca — Top Sunglass" loading="lazy" />
    </div>
    <div class="hero-banner-slide">
      <img src="/images/social_carro_preto.jpg" alt="TOP Sunglass — estilo urbano" loading="lazy" />
    </div>
    <div class="hero-banner-slide">
      <img src="/images/social_praia.jpg" alt="Coleção Praia — lifestyle de verão" loading="lazy" />
    </div>
    <div class="hero-banner-slide">
      <img src="/images/social_ciclista.jpg" alt="Linha Esportivo — para quem não para" loading="lazy" />
    </div>
    <div class="hero-banner-slide">
      <img src="/images/social_alok.jpg" alt="Modelo Alok — estilo praiano" loading="lazy" />
    </div>
    <div class="hero-banner-slide">
      <img src="/images/p9_performance.jpg" alt="TOP Performance — lente vermelha espelhada" loading="lazy" />
    </div>
    <!-- text overlay -->
    <div class="hero-banner-overlay">
      <p class="brandmark">TOP SUNGLASS</p>
      <h1>Para quem vive<br/><em>além</em> do comum.</h1>
      <p class="lede">28 modelos em acetato premium e metal — clássico, streetwear, praia e esportivo.</p>
      <span class="hero-promo">🔥 Compre 2, Leve 3</span>
    </div>
    <button class="hero-banner-prev" id="bannerPrev" aria-label="Foto anterior">&#8249;</button>
    <button class="hero-banner-next" id="bannerNext" aria-label="Próxima foto">&#8250;</button>
    <div class="hero-banner-dots" id="bannerDots">
      <button class="hero-banner-dot is-active" aria-label="Foto 1"></button>
      <button class="hero-banner-dot" aria-label="Foto 2"></button>
      <button class="hero-banner-dot" aria-label="Foto 3"></button>
      <button class="hero-banner-dot" aria-label="Foto 4"></button>
      <button class="hero-banner-dot" aria-label="Foto 5"></button>
      <button class="hero-banner-dot" aria-label="Foto 6"></button>
      <button class="hero-banner-dot" aria-label="Foto 7"></button>
    </div>
  </div>
  <div class="hero-below">
    <div class="wrap">
      <ul class="features">
        <li><b>UV400</b> proteção total contra UVA e UVB</li>
        <li><b>Acetato premium</b> leve e resistente</li>
        <li><b>Compre 2, Leve 3</b> na compra de qualquer modelo</li>
        <li><b>Design atemporal</b> unissex</li>
      </ul>
      <nav class="collections-nav">
        <a href="#promo" style="color:var(--gold);font-weight:800;">🔥 Pague 2, Leve 3</a>
        <a href="#classico">Clássico <span class="count">(11)</span></a>
        <a href="#streetwear">Streetwear <span class="count">(7)</span></a>
        <a href="#praia">Praia <span class="count">(4)</span></a>
        <a href="#esportivo">Esportivo <span class="count">(6)</span></a>
      </nav>
    </div>
  </div>
</div>

<div class="wrap">

  <section class="promo-section" id="promo">
    <div class="promo-head">
      <span class="promo-badge-big">🔥 Oferta especial</span>
      <h2>Pague 2, <em>Leve 3</em></h2>
      <p>Escolha qualquer 2 modelos e leve o 3º de graça — monta o kit que quiser, mistura estilos, presenteia quem você ama. Válido para toda a coleção.</p>
    </div>

    <div class="promo-howto">
      <div class="promo-howto-steps">
        <div class="promo-step">
          <div class="promo-step-num">1</div>
          <div class="promo-step-text">
            <strong>Escolha 3 modelos</strong>
            <span>Pode misturar qualquer linha</span>
          </div>
        </div>
        <div class="promo-step">
          <div class="promo-step-num">2</div>
          <div class="promo-step-text">
            <strong>Fale no WhatsApp</strong>
            <span>Monte seu kit com a gente</span>
          </div>
        </div>
        <div class="promo-step">
          <div class="promo-step-num">3</div>
          <div class="promo-step-text">
            <strong>Pague só 2</strong>
            <span>O mais barato sai de graça</span>
          </div>
        </div>
      </div>
      <a href="https://wa.me/5511940249381?text=Oi%21%20Quero%20montar%20meu%20kit%20Pague%202%20Leve%203%20da%20TOP%20Sunglass%21" class="promo-cta" target="_blank" rel="noopener">Montar meu kit agora</a>
    </div>

    <div class="promo-grid">

      <article class="promo-card">
        <span class="promo-ribbon">Pague 2 Leve 3</span>
        <div class="card-img">
          <button type="button" class="zoom-trigger" data-name="TOP Bauhaus" aria-label="Ver foto de TOP Bauhaus">
            <img src="/images/p1_bauhaus.jpg" alt="TOP Bauhaus" loading="lazy" />
          </button>
        </div>
        <div class="card-body">
          <h3>TOP Bauhaus</h3>
          <p class="desc">Clássico em acetato tartaruga. O favorito da coleção.</p>
          <div class="buy-row">
            <div class="promo-price-row">
              <span class="promo-price-tag">Kit 3 und.</span>
              <span class="promo-price-kit">R$ 99,90 <small>/ 3 pares</small></span>
            </div>
            <a class="promo-cta" href="https://wa.me/5511940249381?text=Quero%20o%20kit%20Pague%202%20Leve%203%20com%20TOP%20Bauhaus!" target="_blank" rel="noopener">Pegar kit</a>
          </div>
        </div>
      </article>

      <article class="promo-card">
        <span class="promo-ribbon">Pague 2 Leve 3</span>
        <div class="card-img">
          <button type="button" class="zoom-trigger" data-name="TOP Alok" aria-label="Ver foto de TOP Alok">
            <img src="/images/p29_alok.jpg" alt="TOP Alok" loading="lazy" />
          </button>
        </div>
        <div class="card-body">
          <h3>TOP Alok</h3>
          <p class="desc">O óculos da vibe. Streetwear raiz, sem esforço.</p>
          <div class="buy-row">
            <div class="promo-price-row">
              <span class="promo-price-tag">Kit 3 und.</span>
              <span class="promo-price-kit">R$ 99,90 <small>/ 3 pares</small></span>
            </div>
            <a class="promo-cta" href="https://wa.me/5511940249381?text=Quero%20o%20kit%20Pague%202%20Leve%203%20com%20TOP%20Alok!" target="_blank" rel="noopener">Pegar kit</a>
          </div>
        </div>
      </article>

      <article class="promo-card">
        <span class="promo-ribbon">Pague 2 Leve 3</span>
        <div class="card-img">
          <button type="button" class="zoom-trigger" data-name="TOP Aviador Cinza" aria-label="Ver foto de TOP Aviador">
            <img src="/images/p6_aviador_cinza.jpg" alt="TOP Aviador Cinza" loading="lazy" />
          </button>
        </div>
        <div class="card-body">
          <h3>TOP Aviador</h3>
          <p class="desc">O clássico de todos os tempos em cinza intemporal.</p>
          <div class="buy-row">
            <div class="promo-price-row">
              <span class="promo-price-tag">Kit 3 und.</span>
              <span class="promo-price-kit">R$ 99,90 <small>/ 3 pares</small></span>
            </div>
            <a class="promo-cta" href="https://wa.me/5511940249381?text=Quero%20o%20kit%20Pague%202%20Leve%203%20com%20TOP%20Aviador!" target="_blank" rel="noopener">Pegar kit</a>
          </div>
        </div>
      </article>

      <article class="promo-card">
        <span class="promo-ribbon">Pague 2 Leve 3</span>
        <div class="card-img">
          <button type="button" class="zoom-trigger" data-name="TOP Performance" aria-label="Ver foto de TOP Performance">
            <img src="/images/p9_performance.jpg" alt="TOP Performance" loading="lazy" />
          </button>
        </div>
        <div class="card-body">
          <h3>TOP Performance</h3>
          <p class="desc">Lente vermelha espelhada, feita pra quem vai além.</p>
          <div class="buy-row">
            <div class="promo-price-row">
              <span class="promo-price-tag">Kit 3 und.</span>
              <span class="promo-price-kit">R$ 99,90 <small>/ 3 pares</small></span>
            </div>
            <a class="promo-cta" href="https://wa.me/5511940249381?text=Quero%20o%20kit%20Pague%202%20Leve%203%20com%20TOP%20Performance!" target="_blank" rel="noopener">Pegar kit</a>
          </div>
        </div>
      </article>

      <article class="promo-card">
        <span class="promo-ribbon">Pague 2 Leve 3</span>
        <div class="card-img">
          <button type="button" class="zoom-trigger" data-name="TOP Maré" aria-label="Ver foto de TOP Maré">
            <img src="/images/p19_mare.jpg" alt="TOP Maré" loading="lazy" />
          </button>
        </div>
        <div class="card-body">
          <h3>TOP Maré</h3>
          <p class="desc">Praia, liberdade e sal — o espírito carioca em acetato.</p>
          <div class="buy-row">
            <div class="promo-price-row">
              <span class="promo-price-tag">Kit 3 und.</span>
              <span class="promo-price-kit">R$ 99,90 <small>/ 3 pares</small></span>
            </div>
            <a class="promo-cta" href="https://wa.me/5511940249381?text=Quero%20o%20kit%20Pague%202%20Leve%203%20com%20TOP%20Mar%C3%A9!" target="_blank" rel="noopener">Pegar kit</a>
          </div>
        </div>
      </article>

      <article class="promo-card">
        <span class="promo-ribbon">Pague 2 Leve 3</span>
        <div class="card-img">
          <button type="button" class="zoom-trigger" data-name="TOP Jaguar" aria-label="Ver foto de TOP Jaguar">
            <img src="/images/p14_jaguar_marrom.jpg" alt="TOP Jaguar" loading="lazy" />
          </button>
        </div>
        <div class="card-body">
          <h3>TOP Jaguar</h3>
          <p class="desc">Degradê marrom, atitude streetwear com toque sofisticado.</p>
          <div class="buy-row">
            <div class="promo-price-row">
              <span class="promo-price-tag">Kit 3 und.</span>
              <span class="promo-price-kit">R$ 99,90 <small>/ 3 pares</small></span>
            </div>
            <a class="promo-cta" href="https://wa.me/5511940249381?text=Quero%20o%20kit%20Pague%202%20Leve%203%20com%20TOP%20Jaguar!" target="_blank" rel="noopener">Pegar kit</a>
          </div>
        </div>
      </article>

    </div>
    <p style="text-align:center;color:var(--ink-muted);font-size:13px;margin:24px 0 0;">* Todos os 28 modelos participam da promoção. Monte o kit que quiser no WhatsApp.</p>
  </section>

    <section class="collection" id="classico">
      <div class="collection-head">
        <h2>Clássico</h2>
        <p>Formas atemporais, acabamento de colecionador.</p>
      </div>
      <div class="grid">
    <article class="card">
      <div class="card-img">
        <button type="button" class="zoom-trigger" data-name="TOP Bauhaus" aria-label="Ver foto inteira de TOP Bauhaus">
          <img src="/images/p1_bauhaus.jpg" alt="Óculos de sol TOP Bauhaus" loading="lazy" />
        </button>
      </div>
      <div class="card-body">
        <h3>TOP Bauhaus</h3>
        <p class="desc">Acetato tartaruga, armação oversized, atitude arquitetônica.</p>
        <p class="tag">&ldquo;Elegância em cada detalhe.&rdquo;</p>
        
        <div class="buy-row">
          <span class="price">R$ 69,90</span>
          <a class="pill" href="https://wa.me/5511940249381?text=Oi%21%20Tenho%20interesse%20no%20TOP%20Bauhaus%20%28R%24%2069%2C90%29%20da%20TOP%20Sunglass." target="_blank" rel="noopener">Comprar no WhatsApp</a>
        </div>
      </div>
    </article>
    <article class="card">
      <div class="card-img">
        <button type="button" class="zoom-trigger" data-name="TOP Vintage Italia" aria-label="Ver foto inteira de TOP Vintage Italia">
          <img src="/images/p11_vintage_italia.jpg" alt="Óculos de sol TOP Vintage Italia" loading="lazy" />
        </button>
      </div>
      <div class="card-body">
        <h3>TOP Vintage Italia</h3>
        <p class="desc">Retangular retrô em tons de âmbar, inspirado nas ruas de Milão.</p>
        
        
        <div class="buy-row">
          <span class="price">R$ 69,90</span>
          <a class="pill" href="https://wa.me/5511940249381?text=Oi%21%20Tenho%20interesse%20no%20TOP%20Vintage%20Italia%20%28R%24%2069%2C90%29%20da%20TOP%20Sunglass." target="_blank" rel="noopener">Comprar no WhatsApp</a>
        </div>
      </div>
    </article>
    <article class="card">
      <div class="card-img">
        <button type="button" class="zoom-trigger" data-name="TOP Heritage Gold" aria-label="Ver foto inteira de TOP Heritage Gold">
          <img src="/images/p10_vintage_dourado.jpg" alt="Óculos de sol TOP Heritage Gold" loading="lazy" />
        </button>
      </div>
      <div class="card-body">
        <h3>TOP Heritage Gold</h3>
        <p class="desc">Metal dourado e acetato escuro num desenho de colecionador.</p>
        
        
        <div class="buy-row">
          <span class="price">R$ 69,90</span>
          <a class="pill" href="https://wa.me/5511940249381?text=Oi%21%20Tenho%20interesse%20no%20TOP%20Heritage%20Gold%20%28R%24%2069%2C90%29%20da%20TOP%20Sunglass." target="_blank" rel="noopener">Comprar no WhatsApp</a>
        </div>
      </div>
    </article>
    <article class="card">
      <div class="card-img">
        <button type="button" class="zoom-trigger" data-name="TOP Rio" aria-label="Ver foto inteira de TOP Rio">
          <img src="/images/p2_redondo_preto.jpg" alt="Óculos de sol TOP Rio" loading="lazy" />
        </button>
      </div>
      <div class="card-body">
        <h3>TOP Rio</h3>
        <p class="desc">Redondo preto, o clássico que nunca sai de moda.</p>
        
        
        <div class="buy-row">
          <span class="price">R$ 69,90</span>
          <a class="pill" href="https://wa.me/5511940249381?text=Oi%21%20Tenho%20interesse%20no%20TOP%20Rio%20%28R%24%2069%2C90%29%20da%20TOP%20Sunglass." target="_blank" rel="noopener">Comprar no WhatsApp</a>
        </div>
      </div>
    </article>
    <article class="card">
      <div class="card-img">
        <button type="button" class="zoom-trigger" data-name="TOP Retrô" aria-label="Ver foto inteira de TOP Retrô">
          <img src="/images/p6_retro_laranja.jpg" alt="Óculos de sol TOP Retrô" loading="lazy" />
        </button>
      </div>
      <div class="card-body">
        <h3>TOP Retrô</h3>
        <p class="desc">Lente âmbar, contorno arredondado, charme dos anos 70.</p>
        
        
        <div class="buy-row">
          <span class="price">R$ 69,90</span>
          <a class="pill" href="https://wa.me/5511940249381?text=Oi%21%20Tenho%20interesse%20no%20TOP%20Retr%C3%B4%20%28R%24%2069%2C90%29%20da%20TOP%20Sunglass." target="_blank" rel="noopener">Comprar no WhatsApp</a>
        </div>
      </div>
    </article>
    <article class="card">
      <div class="card-img">
        <button type="button" class="zoom-trigger" data-name="TOP Aviador — Cinza Clássico" aria-label="Ver foto inteira de TOP Aviador — Cinza Clássico">
          <img src="/images/p13_aviador_cinza.jpg" alt="Óculos de sol TOP Aviador — Cinza Clássico" loading="lazy" />
        </button>
      </div>
      <div class="card-body">
        <h3>TOP Aviador — Cinza Clássico</h3>
        <p class="desc">Aviador em metal preto fosco, lente cinza degradê.</p>
        
        
        <div class="buy-row">
          <span class="price">R$ 69,90</span>
          <a class="pill" href="https://wa.me/5511940249381?text=Oi%21%20Tenho%20interesse%20no%20TOP%20Aviador%20%E2%80%94%20Cinza%20Cl%C3%A1ssico%20%28R%24%2069%2C90%29%20da%20TOP%20Sunglass." target="_blank" rel="noopener">Comprar no WhatsApp</a>
        </div>
      </div>
    </article>
    <article class="card">
      <div class="card-img">
        <button type="button" class="zoom-trigger" data-name="TOP Bambu" aria-label="Ver foto inteira de TOP Bambu">
          <img src="/images/p15_bambu.jpg" alt="Óculos de sol TOP Bambu" loading="lazy" />
        </button>
      </div>
      <div class="card-body">
        <h3>TOP Bambu</h3>
        <p class="desc">Armação preta fosca com hastes em bambu natural.</p>
        
        
        <div class="buy-row">
          <span class="price">R$ 29,90</span>
          <a class="pill" href="https://wa.me/5511940249381?text=Oi%21%20Tenho%20interesse%20no%20TOP%20Bambu%20%28R%24%2029%2C90%29%20da%20TOP%20Sunglass." target="_blank" rel="noopener">Comprar no WhatsApp</a>
        </div>
      </div>
    </article>
    <article class="card">
      <div class="card-img">
        <button type="button" class="zoom-trigger" data-name="TOP Bauhaus — Âmbar" aria-label="Ver foto inteira de TOP Bauhaus — Âmbar">
          <img src="/images/p23_bauhaus_ambar.jpg" alt="Óculos de sol TOP Bauhaus — Âmbar" loading="lazy" />
        </button>
      </div>
      <div class="card-body">
        <h3>TOP Bauhaus — Âmbar</h3>
        <p class="desc">Mesmo Bauhaus oversized, versão em lente âmbar.</p>
        
        
        <div class="buy-row">
          <span class="price">R$ 69,90</span>
          <a class="pill" href="https://wa.me/5511940249381?text=Oi%21%20Tenho%20interesse%20no%20TOP%20Bauhaus%20%E2%80%94%20%C3%82mbar%20%28R%24%2069%2C90%29%20da%20TOP%20Sunglass." target="_blank" rel="noopener">Comprar no WhatsApp</a>
        </div>
      </div>
    </article>
    <article class="card">
      <div class="card-img">
        <button type="button" class="zoom-trigger" data-name="TOP Ipanema" aria-label="Ver foto inteira de TOP Ipanema">
          <img src="/images/p24_ipanema.jpg" alt="Óculos de sol TOP Ipanema" loading="lazy" />
        </button>
      </div>
      <div class="card-body">
        <h3>TOP Ipanema</h3>
        <p class="desc">Quadrado preto oversized, hastes em textura trançada.</p>
        
        
        <div class="buy-row">
          <span class="price">R$ 69,90</span>
          <a class="pill" href="https://wa.me/5511940249381?text=Oi%21%20Tenho%20interesse%20no%20TOP%20Ipanema%20%28R%24%2069%2C90%29%20da%20TOP%20Sunglass." target="_blank" rel="noopener">Comprar no WhatsApp</a>
        </div>
      </div>
    </article>
    <article class="card">
      <div class="card-img">
        <button type="button" class="zoom-trigger" data-name="TOP Ébano" aria-label="Ver foto inteira de TOP Ébano">
          <img src="/images/p28_ebano.jpg" alt="Óculos de sol TOP Ébano" loading="lazy" />
        </button>
      </div>
      <div class="card-body">
        <h3>TOP Ébano</h3>
        <p class="desc">Redondo preto com hastes em madeira escura, acabamento dourado.</p>
        <p class="tag">&ldquo;Mais que óculos. É presença.&rdquo;</p>
        
        <div class="buy-row">
          <span class="price">R$ 69,90</span>
          <a class="pill" href="https://wa.me/5511940249381?text=Oi%21%20Tenho%20interesse%20no%20TOP%20%C3%89bano%20%28R%24%2069%2C90%29%20da%20TOP%20Sunglass." target="_blank" rel="noopener">Comprar no WhatsApp</a>
        </div>
      </div>
    </article>
    <article class="card">
      <div class="card-img">
        <button type="button" class="zoom-trigger" data-name="TOP Alok" aria-label="Ver foto inteira de TOP Alok">
          <img src="/images/p29_alok.jpg" alt="Óculos de sol TOP Alok" loading="lazy" />
        </button>
      </div>
      <div class="card-body">
        <h3>TOP Alok</h3>
        <p class="desc">Redondo preto com ponte dupla em metal — o modelo visto por aí.</p>
        
        
        <div class="buy-row">
          <span class="price">R$ 29,90</span>
          <a class="pill" href="https://wa.me/5511940249381?text=Oi%21%20Tenho%20interesse%20no%20TOP%20Alok%20%28R%24%2029%2C90%29%20da%20TOP%20Sunglass." target="_blank" rel="noopener">Comprar no WhatsApp</a>
        </div>
      </div>
    </article></div>
    </section>
    <section class="collection" id="streetwear">
      <div class="collection-head">
        <h2>Streetwear</h2>
        <p>Volume, geometria e presença de rua.</p>
      </div>
      <div class="grid">
    <article class="card">
      <div class="card-img">
        <button type="button" class="zoom-trigger" data-name="TOP Bold" aria-label="Ver foto inteira de TOP Bold">
          <img src="/images/p7_square_bold.jpg" alt="Óculos de sol TOP Bold" loading="lazy" />
        </button>
      </div>
      <div class="card-body">
        <h3>TOP Bold</h3>
        <p class="desc">Quadrado grande, lente âmbar, presença que não passa despercebida.</p>
        <p class="tag">&ldquo;Estilo que valoriza você.&rdquo;</p>
        
        <div class="buy-row">
          <span class="price">R$ 69,90</span>
          <a class="pill" href="https://wa.me/5511940249381?text=Oi%21%20Tenho%20interesse%20no%20TOP%20Bold%20%28R%24%2069%2C90%29%20da%20TOP%20Sunglass." target="_blank" rel="noopener">Comprar no WhatsApp</a>
        </div>
      </div>
    </article>
    <article class="card">
      <div class="card-img">
        <button type="button" class="zoom-trigger" data-name="TOP Hexa" aria-label="Ver foto inteira de TOP Hexa">
          <img src="/images/p3_hexagonal.jpg" alt="Óculos de sol TOP Hexa" loading="lazy" />
        </button>
      </div>
      <div class="card-body">
        <h3>TOP Hexa</h3>
        <p class="desc">Corte hexagonal em dourado — geometria com atitude.</p>
        
        
        <div class="buy-row">
          <span class="price">R$ 69,90</span>
          <a class="pill" href="https://wa.me/5511940249381?text=Oi%21%20Tenho%20interesse%20no%20TOP%20Hexa%20%28R%24%2069%2C90%29%20da%20TOP%20Sunglass." target="_blank" rel="noopener">Comprar no WhatsApp</a>
        </div>
      </div>
    </article>
    <article class="card">
      <div class="card-img">
        <button type="button" class="zoom-trigger" data-name="TOP Aura" aria-label="Ver foto inteira de TOP Aura">
          <img src="/images/p12_rimless.jpg" alt="Óculos de sol TOP Aura" loading="lazy" />
        </button>
      </div>
      <div class="card-body">
        <h3>TOP Aura</h3>
        <p class="desc">Sem aro, lente degradê rosa e dourado — minimalismo statement.</p>
        
        
        <div class="buy-row">
          <span class="price">R$ 69,90</span>
          <a class="pill" href="https://wa.me/5511940249381?text=Oi%21%20Tenho%20interesse%20no%20TOP%20Aura%20%28R%24%2069%2C90%29%20da%20TOP%20Sunglass." target="_blank" rel="noopener">Comprar no WhatsApp</a>
        </div>
      </div>
    </article>
    <article class="card">
      <div class="card-img">
        <button type="button" class="zoom-trigger" data-name="TOP Square — Azul Espelhado" aria-label="Ver foto inteira de TOP Square — Azul Espelhado">
          <img src="/images/p16_square_azul.jpg" alt="Óculos de sol TOP Square — Azul Espelhado" loading="lazy" />
        </button>
      </div>
      <div class="card-body">
        <h3>TOP Square — Azul Espelhado</h3>
        <p class="desc">Quadrado preto fosco, lente azul espelhada, acompanha estojo.</p>
        
        
        <div class="buy-row">
          <span class="price">R$ 69,90</span>
          <a class="pill" href="https://wa.me/5511940249381?text=Oi%21%20Tenho%20interesse%20no%20TOP%20Square%20%E2%80%94%20Azul%20Espelhado%20%28R%24%2069%2C90%29%20da%20TOP%20Sunglass." target="_blank" rel="noopener">Comprar no WhatsApp</a>
        </div>
      </div>
    </article>
    <article class="card">
      <div class="card-img">
        <button type="button" class="zoom-trigger" data-name="TOP Jaguar — Marrom Degradê" aria-label="Ver foto inteira de TOP Jaguar — Marrom Degradê">
          <img src="/images/p20_jaguar_marrom.jpg" alt="Óculos de sol TOP Jaguar — Marrom Degradê" loading="lazy" />
        </button>
      </div>
      <div class="card-body">
        <h3>TOP Jaguar — Marrom Degradê</h3>
        <p class="desc">Sem aro, hastes em metal dourado com detalhe de onça, lente marrom degradê.</p>
        
        
        <div class="buy-row">
          <span class="price">R$ 69,90</span>
          <a class="pill" href="https://wa.me/5511940249381?text=Oi%21%20Tenho%20interesse%20no%20TOP%20Jaguar%20%E2%80%94%20Marrom%20Degrad%C3%AA%20%28R%24%2069%2C90%29%20da%20TOP%20Sunglass." target="_blank" rel="noopener">Comprar no WhatsApp</a>
        </div>
      </div>
    </article>
    <article class="card">
      <div class="card-img">
        <button type="button" class="zoom-trigger" data-name="TOP Jaguar — Rosé Degradê" aria-label="Ver foto inteira de TOP Jaguar — Rosé Degradê">
          <img src="/images/p21_jaguar_rose.jpg" alt="Óculos de sol TOP Jaguar — Rosé Degradê" loading="lazy" />
        </button>
      </div>
      <div class="card-body">
        <h3>TOP Jaguar — Rosé Degradê</h3>
        <p class="desc">Mesma armação Jaguar, lente rosé degradê, acompanha estojo TOP.</p>
        
        
        <div class="buy-row">
          <span class="price">R$ 69,90</span>
          <a class="pill" href="https://wa.me/5511940249381?text=Oi%21%20Tenho%20interesse%20no%20TOP%20Jaguar%20%E2%80%94%20Ros%C3%A9%20Degrad%C3%AA%20%28R%24%2069%2C90%29%20da%20TOP%20Sunglass." target="_blank" rel="noopener">Comprar no WhatsApp</a>
        </div>
      </div>
    </article>
    <article class="card">
      <div class="card-img">
        <button type="button" class="zoom-trigger" data-name="TOP Jaguar — Azul Degradê" aria-label="Ver foto inteira de TOP Jaguar — Azul Degradê">
          <img src="/images/p22_jaguar_azul.jpg" alt="Óculos de sol TOP Jaguar — Azul Degradê" loading="lazy" />
        </button>
      </div>
      <div class="card-body">
        <h3>TOP Jaguar — Azul Degradê</h3>
        <p class="desc">Mesma armação Jaguar, lente azul-para-rosé degradê, acompanha estojo TOP.</p>
        
        
        <div class="buy-row">
          <span class="price">R$ 69,90</span>
          <a class="pill" href="https://wa.me/5511940249381?text=Oi%21%20Tenho%20interesse%20no%20TOP%20Jaguar%20%E2%80%94%20Azul%20Degrad%C3%AA%20%28R%24%2069%2C90%29%20da%20TOP%20Sunglass." target="_blank" rel="noopener">Comprar no WhatsApp</a>
        </div>
      </div>
    </article></div>
    </section>
    <section class="collection" id="praia">
      <div class="collection-head">
        <h2>Praia</h2>
        <p>Leveza e cor para o dia inteiro no sol.</p>
      </div>
      <div class="grid">
    <article class="card">
      <div class="card-img">
        <button type="button" class="zoom-trigger" data-name="TOP Maré" aria-label="Ver foto inteira de TOP Maré">
          <img src="/images/p4_cateye.jpg" alt="Óculos de sol TOP Maré" loading="lazy" />
        </button>
      </div>
      <div class="card-body">
        <h3>TOP Maré</h3>
        <p class="desc">Cat-eye em cristal azul, feito pros dias de sol na areia.</p>
        
        
        <div class="buy-row">
          <span class="price">R$ 69,90</span>
          <a class="pill" href="https://wa.me/5511940249381?text=Oi%21%20Tenho%20interesse%20no%20TOP%20Mar%C3%A9%20%28R%24%2069%2C90%29%20da%20TOP%20Sunglass." target="_blank" rel="noopener">Comprar no WhatsApp</a>
        </div>
      </div>
    </article>
    <article class="card">
      <div class="card-img">
        <button type="button" class="zoom-trigger" data-name="TOP Essence" aria-label="Ver foto inteira de TOP Essence">
          <img src="/images/p5_essence.jpg" alt="Óculos de sol TOP Essence" loading="lazy" />
        </button>
      </div>
      <div class="card-body">
        <h3>TOP Essence</h3>
        <p class="desc">Redondo em acetato premium, cristal acinzentado e hastes tártaro — também sai em marrom e preto.</p>
        <p class="tag">&ldquo;Estilo que protege. Proteção que dura.&rdquo;</p>
        <div class="specs"><div class="spec"><span>Frontal</span><b>142 mm</b></div><div class="spec"><span>Lente</span><b>51 mm</b></div><div class="spec"><span>Ponte</span><b>20 mm</b></div><div class="spec"><span>Haste</span><b>145 mm</b></div><div class="spec"><span>Encaixe</span><b>Unissex</b></div></div>
        <div class="buy-row">
          <span class="price">R$ 69,90</span>
          <a class="pill" href="https://wa.me/5511940249381?text=Oi%21%20Tenho%20interesse%20no%20TOP%20Essence%20%28R%24%2069%2C90%29%20da%20TOP%20Sunglass." target="_blank" rel="noopener">Comprar no WhatsApp</a>
        </div>
      </div>
    </article>
    <article class="card">
      <div class="card-img">
        <button type="button" class="zoom-trigger" data-name="TOP Clarity — Transparente" aria-label="Ver foto inteira de TOP Clarity — Transparente">
          <img src="/images/p25_clarity_transparente.jpg" alt="Óculos de sol TOP Clarity — Transparente" loading="lazy" />
        </button>
      </div>
      <div class="card-body">
        <h3>TOP Clarity — Transparente</h3>
        <p class="desc">Quadrado oversized em acetato cristal, detalhe tartaruga e dourado na haste.</p>
        
        
        <div class="buy-row">
          <span class="price">R$ 69,90</span>
          <a class="pill" href="https://wa.me/5511940249381?text=Oi%21%20Tenho%20interesse%20no%20TOP%20Clarity%20%E2%80%94%20Transparente%20%28R%24%2069%2C90%29%20da%20TOP%20Sunglass." target="_blank" rel="noopener">Comprar no WhatsApp</a>
        </div>
      </div>
    </article>
    <article class="card">
      <div class="card-img">
        <button type="button" class="zoom-trigger" data-name="TOP Clarity — Marrom" aria-label="Ver foto inteira de TOP Clarity — Marrom">
          <img src="/images/p26_clarity_marrom.jpg" alt="Óculos de sol TOP Clarity — Marrom" loading="lazy" />
        </button>
      </div>
      <div class="card-body">
        <h3>TOP Clarity — Marrom</h3>
        <p class="desc">Mesmo Clarity oversized, versão em acetato marrom translúcido.</p>
        
        
        <div class="buy-row">
          <span class="price">R$ 69,90</span>
          <a class="pill" href="https://wa.me/5511940249381?text=Oi%21%20Tenho%20interesse%20no%20TOP%20Clarity%20%E2%80%94%20Marrom%20%28R%24%2069%2C90%29%20da%20TOP%20Sunglass." target="_blank" rel="noopener">Comprar no WhatsApp</a>
        </div>
      </div>
    </article></div>
    </section>
    <section class="collection" id="esportivo">
      <div class="collection-head">
        <h2>Esportivo</h2>
        <p>Encaixe firme, lente de alta performance.</p>
      </div>
      <div class="grid">
    <article class="card">
      <div class="card-img">
        <button type="button" class="zoom-trigger" data-name="TOP Performance — Vermelho Espelhado" aria-label="Ver foto inteira de TOP Performance — Vermelho Espelhado">
          <img src="/images/p9_performance.jpg" alt="Óculos de sol TOP Performance — Vermelho Espelhado" loading="lazy" />
        </button>
      </div>
      <div class="card-body">
        <h3>TOP Performance — Vermelho Espelhado</h3>
        <p class="desc">Wrap esportivo preto e vermelho, lente vermelha espelhada, logo TOP na haste.</p>
        
        
        <div class="buy-row">
          <span class="price">R$ 69,90</span>
          <a class="pill" href="https://wa.me/5511940249381?text=Oi%21%20Tenho%20interesse%20no%20TOP%20Performance%20%E2%80%94%20Vermelho%20Espelhado%20%28R%24%2069%2C90%29%20da%20TOP%20Sunglass." target="_blank" rel="noopener">Comprar no WhatsApp</a>
        </div>
      </div>
    </article>
    <article class="card">
      <div class="card-img">
        <button type="button" class="zoom-trigger" data-name="TOP Aviador — Azul Espelhado" aria-label="Ver foto inteira de TOP Aviador — Azul Espelhado">
          <img src="/images/p14_aviador_azul.jpg" alt="Óculos de sol TOP Aviador — Azul Espelhado" loading="lazy" />
        </button>
      </div>
      <div class="card-body">
        <h3>TOP Aviador — Azul Espelhado</h3>
        <p class="desc">Mesmo aviador em metal preto, lente azul espelhada.</p>
        
        
        <div class="buy-row">
          <span class="price">R$ 69,90</span>
          <a class="pill" href="https://wa.me/5511940249381?text=Oi%21%20Tenho%20interesse%20no%20TOP%20Aviador%20%E2%80%94%20Azul%20Espelhado%20%28R%24%2069%2C90%29%20da%20TOP%20Sunglass." target="_blank" rel="noopener">Comprar no WhatsApp</a>
        </div>
      </div>
    </article>
    <article class="card">
      <div class="card-img">
        <button type="button" class="zoom-trigger" data-name="TOP Square — Sunset Espelhado" aria-label="Ver foto inteira de TOP Square — Sunset Espelhado">
          <img src="/images/p17_square_sunset.jpg" alt="Óculos de sol TOP Square — Sunset Espelhado" loading="lazy" />
        </button>
      </div>
      <div class="card-body">
        <h3>TOP Square — Sunset Espelhado</h3>
        <p class="desc">Quadrado preto fosco, lente vermelha/laranja espelhada, acompanha estojo.</p>
        
        
        <div class="buy-row">
          <span class="price">R$ 69,90</span>
          <a class="pill" href="https://wa.me/5511940249381?text=Oi%21%20Tenho%20interesse%20no%20TOP%20Square%20%E2%80%94%20Sunset%20Espelhado%20%28R%24%2069%2C90%29%20da%20TOP%20Sunglass." target="_blank" rel="noopener">Comprar no WhatsApp</a>
        </div>
      </div>
    </article>
    <article class="card">
      <div class="card-img">
        <button type="button" class="zoom-trigger" data-name="TOP Performance — Azul Espelhado" aria-label="Ver foto inteira de TOP Performance — Azul Espelhado">
          <img src="/images/p18_performance_azul.jpg" alt="Óculos de sol TOP Performance — Azul Espelhado" loading="lazy" />
        </button>
      </div>
      <div class="card-body">
        <h3>TOP Performance — Azul Espelhado</h3>
        <p class="desc">Wrap esportivo preto e azul, lente azul espelhada, logo TOP na haste.</p>
        
        
        <div class="buy-row">
          <span class="price">R$ 69,90</span>
          <a class="pill" href="https://wa.me/5511940249381?text=Oi%21%20Tenho%20interesse%20no%20TOP%20Performance%20%E2%80%94%20Azul%20Espelhado%20%28R%24%2069%2C90%29%20da%20TOP%20Sunglass." target="_blank" rel="noopener">Comprar no WhatsApp</a>
        </div>
      </div>
    </article>
    <article class="card">
      <div class="card-img">
        <button type="button" class="zoom-trigger" data-name="TOP Performance — Shield Tartaruga" aria-label="Ver foto inteira de TOP Performance — Shield Tartaruga">
          <img src="/images/p19_performance_shield.jpg" alt="Óculos de sol TOP Performance — Shield Tartaruga" loading="lazy" />
        </button>
      </div>
      <div class="card-body">
        <h3>TOP Performance — Shield Tartaruga</h3>
        <p class="desc">Máscara esportiva sem aro, acabamento tartaruga, feita pro treino e a rotina.</p>
        <p class="tag">&ldquo;Performance no esporte. Estilo na rotina.&rdquo;</p>
        
        <div class="buy-row">
          <span class="price">R$ 69,90</span>
          <a class="pill" href="https://wa.me/5511940249381?text=Oi%21%20Tenho%20interesse%20no%20TOP%20Performance%20%E2%80%94%20Shield%20Tartaruga%20%28R%24%2069%2C90%29%20da%20TOP%20Sunglass." target="_blank" rel="noopener">Comprar no WhatsApp</a>
        </div>
      </div>
    </article>
    <article class="card">
      <div class="card-img">
        <button type="button" class="zoom-trigger" data-name="TOP Velocity" aria-label="Ver foto inteira de TOP Velocity">
          <img src="/images/p27_velocity.jpg" alt="Óculos de sol TOP Velocity" loading="lazy" />
        </button>
      </div>
      <div class="card-body">
        <h3>TOP Velocity</h3>
        <p class="desc">Máscara cristal sem aro, lente espelhada azul-violeta degradê.</p>
        <p class="tag">&ldquo;Visão que acompanha seu ritmo.&rdquo;</p>
        
        <div class="buy-row">
          <span class="price">R$ 69,90</span>
          <a class="pill" href="https://wa.me/5511940249381?text=Oi%21%20Tenho%20interesse%20no%20TOP%20Velocity%20%28R%24%2069%2C90%29%20da%20TOP%20Sunglass." target="_blank" rel="noopener">Comprar no WhatsApp</a>
        </div>
      </div>
    </article></div>
    </section>

  
    <section class="social">
      <div class="social-head">
        <h2>TOP em ação</h2>
        <p>Da estrada ao pedal, do carro à praia — a coleção no dia a dia de quem usa.</p>
      </div>
      <div class="social-grid"><div class="social-card">
      <img src="/images/social_alok.jpg" alt="Alok usando óculos TOP Sunglass" loading="lazy" />
      <figcaption>Alok</figcaption>
    </div><div class="social-card">
      <img src="/images/social_carro_preto.jpg" alt="No dia a dia usando óculos TOP Sunglass" loading="lazy" />
      <figcaption>No dia a dia</figcaption>
    </div><div class="social-card">
      <img src="/images/social_ciclista.jpg" alt="Ciclismo usando óculos TOP Sunglass" loading="lazy" />
      <figcaption>Ciclismo</figcaption>
    </div><div class="social-card">
      <img src="/images/social_praia.jpg" alt="Ensaio TOP usando óculos TOP Sunglass" loading="lazy" />
      <figcaption>Ensaio TOP</figcaption>
    </div></div>
    </section>

  <footer>
    <div>
      <p class="fm">TOP SUNGLASS</p>
      <p class="fnote">Valores e disponibilidade sob consulta. Fale com a gente para pedidos e revenda.</p>
    </div>
    <div class="contacts">
      <a class="ig" href="https://instagram.com/top.sunglass" target="_blank" rel="noopener">@top.sunglass</a>
      <a class="wa" href="https://wa.me/5511940249381?text=Oi%21%20Vi%20o%20cat%C3%A1logo%20da%20TOP%20Sunglass%20e%20queria%20saber%20mais." target="_blank" rel="noopener">
        <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M12.04 2C6.58 2 2.13 6.45 2.13 11.91c0 1.75.46 3.45 1.32 4.95L2.05 22l5.25-1.38a9.9 9.9 0 0 0 4.74 1.21h.01c5.46 0 9.91-4.45 9.91-9.92 0-2.65-1.03-5.14-2.9-7.01A9.86 9.86 0 0 0 12.04 2zm5.8 14.1c-.24.68-1.4 1.3-1.93 1.38-.5.08-1.12.11-1.8-.11-.42-.13-.95-.31-1.64-.6-2.88-1.24-4.76-4.14-4.9-4.33-.14-.19-1.17-1.56-1.17-2.97 0-1.41.74-2.1 1-2.39.26-.28.57-.35.76-.35.19 0 .38 0 .55.01.18.01.42-.07.65.5.24.58.81 2 .88 2.15.07.14.12.31.02.5-.09.19-.14.31-.28.47-.14.16-.29.36-.42.48-.14.14-.28.28-.12.56.16.28.7 1.16 1.51 1.88 1.04.93 1.91 1.22 2.19 1.36.28.14.44.12.6-.07.16-.19.68-.79.86-1.06.18-.28.36-.23.6-.14.24.09 1.55.73 1.81.86.26.14.44.19.5.31.06.12.06.68-.18 1.36z"/></svg>
        WhatsApp
      </a>
    </div>
  </footer>
</div>

<a class="wa-float" href="https://wa.me/5511940249381?text=Oi%21%20Vi%20o%20cat%C3%A1logo%20da%20TOP%20Sunglass%20e%20queria%20saber%20mais." target="_blank" rel="noopener" aria-label="Falar no WhatsApp">
  <svg viewBox="0 0 24 24" fill="#ffffff" aria-hidden="true"><path d="M12.04 2C6.58 2 2.13 6.45 2.13 11.91c0 1.75.46 3.45 1.32 4.95L2.05 22l5.25-1.38a9.9 9.9 0 0 0 4.74 1.21h.01c5.46 0 9.91-4.45 9.91-9.92 0-2.65-1.03-5.14-2.9-7.01A9.86 9.86 0 0 0 12.04 2zm5.8 14.1c-.24.68-1.4 1.3-1.93 1.38-.5.08-1.12.11-1.8-.11-.42-.13-.95-.31-1.64-.6-2.88-1.24-4.76-4.14-4.9-4.33-.14-.19-1.17-1.56-1.17-2.97 0-1.41.74-2.1 1-2.39.26-.28.57-.35.76-.35.19 0 .38 0 .55.01.18.01.42-.07.65.5.24.58.81 2 .88 2.15.07.14.12.31.02.5-.09.19-.14.31-.28.47-.14.16-.29.36-.42.48-.14.14-.28.28-.12.56.16.28.7 1.16 1.51 1.88 1.04.93 1.91 1.22 2.19 1.36.28.14.44.12.6-.07.16-.19.68-.79.86-1.06.18-.28.36-.23.6-.14.24.09 1.55.73 1.81.86.26.14.44.19.5.31.06.12.06.68-.18 1.36z"/></svg>
</a>

<div class="lightbox" id="lightbox" role="dialog" aria-modal="true" aria-label="Foto ampliada">
  <button type="button" class="lightbox-close" id="lightboxClose" aria-label="Fechar">&times;</button>
  <figure class="lightbox-fig">
    <img id="lightboxImg" src="" alt="" />
    <figcaption id="lightboxCaption"></figcaption>
  </figure>
</div>`;

export const PRODUCT_COUNT = 28;
